import please2.command.cmd_help
import please2.command.cmd_which_os
import please2.command.cmd_flatten
import please2.command.cmd_filter
import please2.command.cmd_filter_out
import please2.command.cmd_filter_select
import please2.command.cmd_printers_ls
import please2.command.cmd_print
import please2.command.cmd_set_audio_volume
import please2.command.cmd_audio_devices_ls
import please2.command.cmd_extract
import please2.command.cmd_display
import please2.command.build.cmd_build_ls
import please2.command.build.bazel.cmd_bazel_dep_graph
import please2.command.git.cmd_git_help
import please2.command.git.cmd_git_ls_remotes
import please2.command.git.cmd_git_which_branch
import please2.command.git.cmd_git_ls_branches
import please2.command.git.cmd_git_ls_commits
import please2.command.git.cmd_git_new_branch
import please2.command.git.cmd_git_switch_to_branch
import please2.command.git.cmd_git_arrow
import please2.command.docker.cmd_docker_ls_images
import please2.command.docker.cmd_docker_ls_containers
import please2.command.docker.cmd_docker_kill_all_containers
import please2.command.docker.cmd_docker_delete_all_containers
import please2.command.docker.cmd_docker_delete_all_images
import please2.command.alternatives.cmd_alternatives_ls
import please2.command.alternatives.cmd_alternatives_choose
import please2.command.network.cmd_network_devices_ls
import please2.command.github.cmd_github_new_ssh
import please2.command.ssh.cmd_ssh_new
import please2.command.tex.cmd_tex_preview
